In [1]:
import pandas as pd
nember={"A":1,"Z":2,"E":3}
prt=pd.Series(nember)
print(prt)
print(prt["Z"])

A    1
Z    2
E    3
dtype: int64
2

In [2]:
import pandas as pd
nember=[1,2,3]
prt=pd.Series(nember,index=["A","Z","E"])
print(prt)
print(prt["Z"])

A    1
Z    2
E    3
dtype: int64
2

In [3]:
import pandas as pd

calories = {"day1": 420 , "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

day1    420
day2    380
dtype: int64

In [4]:
import pandas as pd
nember=[1,2,3]
tt=pd.Series(nember)
print(tt)

0    1
1    2
2    3
dtype: int64

In [5]:
import os
print(os.getcwd())

C:\Users\IVM\OneDrive\PANDAS

In [6]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df.to_csv('tips.csv', index=False)
print("تم تنزيل وحفظ ملف tips.csv بنجاح في مجلدك!")

تم تنزيل وحفظ ملف tips.csv بنجاح في مجلدك!

In [7]:
import pandas as pd
df=pd.read_csv('tips.csv')
display(df.head())
df.info()
rows ,cols =df.shape
display(rows,cols)
df.describe()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

244

7

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [8]:
import pandas as pd
df=pd.read_csv('tips.csv')
prix=df.total_bill*0.15
display(prix)

0      2.5485
1      1.5510
2      3.1515
3      3.5520
4      3.6885
        ...
239    4.3545
240    4.0770
241    3.4005
242    2.6730
243    2.8170
Name: total_bill, Length: 244, dtype: float64

In [9]:
import pandas as pd
df=pd.read_csv('tips.csv')
df.tip.mean()

np.float64(2.99827868852459)

In [10]:
import pandas as pd
df=pd.read_csv('tips.csv')
display(df.total_bill.max())
df.total_bill.min()

50.81

3.07

In [11]:
import pandas as pd
df=pd.read_csv('tips.csv')
display(df[ df.tip>5])

     total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
44        30.40   5.60    Male     No   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
181       23.33   5.65    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [12]:
import pandas as pd
df=pd.read_csv('tips.csv')
display(df.day.value_counts())

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [13]:
import pandas as pd
df=pd.read_csv('tips.csv')
df.time.str.upper()

0      DINNER
1      DINNER
2      DINNER
3      DINNER
4      DINNER
        ...
239    DINNER
240    DINNER
241    DINNER
242    DINNER
243    DINNER
Name: time, Length: 244, dtype: object

In [14]:
import pandas as pd
df=pd.read_csv('tips.csv')
txt=df.total_bill.apply(lambda x: 'High' if x > 20 else 'Low')
txt.head()

0     Low
1     Low
2    High
3    High
4    High
Name: total_bill, dtype: object

In [15]:
def categorize_bill(price):
    if price > 20:
        return 'High'
    else:
        return 'Low'
tr=(df. total_bill.apply(categorize_bill))
tr.head()

0     Low
1     Low
2    High
3    High
4    High
Name: total_bill, dtype: object

In [16]:
import pandas as pd
df=pd.read_csv('tips.csv')
nin=df.tip.sort_values(ascending=False)
nin.head()

170    10.00
212     9.00
23      7.58
59      6.73
141     6.70
Name: tip, dtype: float64

In [17]:
import pandas as pd
df=pd.read_csv('tips.csv')
tt=df.total_bill.isnull().sum()
print(tt)

0